name: car_damage_detection
description: "Car Damage Detection using Flutter & YOLOv11"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.1.2
  provider: ^6.1.2
  camera: ^0.11.0+2
  lottie: ^3.2.0
  icons_launcher: ^3.0.0
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          # weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
